name: Docker Image CI

on:
  push:
    branches: [ "main" , "test" ]

env:
  IMAGE_NAME: clock-rest-api

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.timestamp }}
      - name: Tag this image with latest tag
        run: docker tag ${{ env.IMAGE_NAME }}:${{ steps.timestamp.outputs.timestamp }} ghcr.io/tachyonknave/${{ env.IMAGE_NAME }}:latest
      - name: Push image to GHCR
        run: docker push ghcr.io/tachyonknave/${{ env.IMAGE_NAME }}:latest
