name: Tests

on:
  push:
    branches: [ "main" , "behave" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLOCK_URL: http://localhost:5000/


jobs:
  behave-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull prebuilt Docker image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Run Docker container in detached mode
        run: >
          docker run -d --rm -p 5000:5000 --name test-container 
          -e CLOCK_URL=${{ env.CLOCK_URL }} 
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Wait for service to be ready
        run: |
          echo "Waiting for container to be ready..."
          for i in {1..15}; do
            if curl -s --fail http://localhost:5000/health; then
              echo "Container is ready!"
              exit 0
            fi
            sleep 2
          done
          echo "Container did not become ready in time."
          exit 1

      - name: Run tests
        run: make integration

      - name: Stop container
        if: always()
        run: docker stop test-container
